import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { PrismaClient, Prisma } from '@prisma/client'


const prisma = new PrismaClient()
export async function getServerSideProps() {


  const todo = await prisma.todo.findMany()
  return {
    props: {
      initialTodo: todo
    }, // will be passed to the page component as props
  }
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.container}>
        <div className={styles.description}>
          <h1>
            Board
 
          </h1>
        </div>
         
        </div>
      </main>
    </>
  )
}
